---
name: codespell_columns
description: Check code for common misspellings.
homepage: https://github.com/paramSonawane/codespell_columns
licenses:
  - GPL-2.0-or-later
languages: []
categories:
  - Linter
source:
  id: pkg:github/paramSonawane/codespell_columns@v2.2.7-alpha
  build:
    run: |
      pip install --target=./dist .

bin:
  codespell: dist/bin/codespell
